version: '3.7'

services: 
  api:
    image : a
    restart: always
    links:
      - mongodb
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./aa
    ports:
      - 27017:27017
    
    working_dir: /dir
    container_name: my-web-container


